language: ruby

rvm:
  - 2.1
  - 2.2.3
  - 2.3.0
gemfile:
  - gemfiles/Gemfile.ar-4.2
  - gemfiles/Gemfile.ar-5.0

env:
  - TIMEZONE_AWARE=1 POSTGRES=1 MYSQL=1
  - TIMEZONE_AWARE=0 POSTGRES=1 MYSQL=1

addons:
  postgresql: 9.3

sudo: false
cache: bundler

before_script:
  - mysql -e 'create database typed_store_test;'
  - psql -c 'create database typed_store_test;' -U postgres

matrix:
  exclude:
    - rvm: 2.1
      gemfile: gemfiles/Gemfile.ar-5.0
