rvm:
  - 1.9.3
  - 2.0.0
gemfile:
  - gemfiles/Gemfile.ar-3.2
  - gemfiles/Gemfile.ar-4.0
  - gemfiles/Gemfile.ar-edge

before_script:
  - mysql -e 'create database typed_store_test;'
  - psql -c 'create database typed_store_test;' -U postgres

env: POSTGRES=1 MYSQL=1 POSTGRES_URL=$(curl http://api.postgression.com)
