language: ruby

rvm:
  - 2.3.5
  - 2.4.4
gemfile:
  - gemfiles/Gemfile.ar-4.2
  - gemfiles/Gemfile.ar-5.0
  - gemfiles/Gemfile.ar-5.1
  - gemfiles/Gemfile.ar-5.2
  - gemfiles/Gemfile.ar-master

env:
  - TIMEZONE_AWARE=1 POSTGRES=1 MYSQL=1
  - TIMEZONE_AWARE=0 POSTGRES=1 MYSQL=1
  - TIMEZONE_AWARE=1 POSTGRES=1 POSTGRES_JSON=1
  - TIMEZONE_AWARE=0 POSTGRES=1 POSTGRES_JSON=1

matrix:
  exclude:
    - rvm: 2.3.5
      gemfile: 'gemfiles/Gemfile.ar-master'

addons:
  postgresql: 9.3

sudo: false
cache: bundler

before_script:
  - mysql -e 'create database typed_store_test;'
  - psql -c 'create database typed_store_test;' -U postgres
