rvm:
  - 1.9.3
  - 2.0.0
gemfile:
  - gemfiles/Gemfile.ar-3.2
  - gemfiles/Gemfile.ar-4.0
  - gemfiles/Gemfile.ar-4.1
  - gemfiles/Gemfile.ar-edge

before_script:
  - mysql -e 'create database typed_store_test;'

env:
  - TIMEZONE_AWARE=1 POSTGRES=1 MYSQL=1 POSTGRES_URL=$(curl http://api.postgression.com)
  - TIMEZONE_AWARE=0 POSTGRES=1 MYSQL=1 POSTGRES_URL=$(curl http://api.postgression.com)

matrix:
  allow_failures:
    - gemfile: gemfiles/Gemfile.ar-edge
